In [10]:
import working_day.return_working_day as wd
import discount_curve.discount_curve as dc
import csv
import pandas as pd
import datetime

def year_to_month(str_year):
        num_year = int(str_year[0:len(str_year)-1])
        return num_year * 12
    
def calc_day_count_fraction(start_date, end_date, convention):
        datetime_obj_start = datetime.datetime.strptime(start_date, '%Y/%m/%d')
        datetime_obj_end = datetime.datetime.strptime(end_date, '%Y/%m/%d')
        day_count_fraction = float((datetime_obj_end - datetime_obj_start).days / convention)
        return day_count_fraction

class swap_pricer:
    def __init__(self, valuation_date, input_file_name, convention_file_name, IR_data_name):
        df_input = pd.read_csv(input_file_name)
        df_convention = pd.read_csv(convention_file_name, index_col=0)
        self._valuation_date = valuation_date
        self._ccy_our_pay = df_input.at[0, 'ccy_our_pay']
        self._ccy_our_rec = df_input.at[0, 'ccy_our_rec']
        self._fix_float_pay = df_input.at[0, 'fixed_or_float_pay_side']
        self._fix_float_rec = df_input.at[0, 'fixed_or_float_rec_side']
        self._term = df_input.at[0, 'term']
        self._notional = df_input.at[0, 'Notional']
        self._dcc_pay = df_convention.at[self._ccy_our_pay, self._fix_float_pay]
        self._dcc_rec = df_convention.at[self._ccy_our_rec, self._fix_float_rec]
        self._roll_pay = df_convention.at[self._ccy_our_pay, 'ROLL']
        self._roll_rec = df_convention.at[self._ccy_our_rec, 'ROLL']
        self._num_pay_side = int(year_to_month(self._term) / int(self._roll_pay[0:len(self._roll_pay)-1]))
        self._num_rec_side = int(year_to_month(self._term) / int(self._roll_rec[0:len(self._roll_rec)-1]))
        self._names_float =  ['start_date', 'end_date', 'payment_date', 'dcf', 'DF', 'foward rate', 'PV']
        self._names_fix = ['start_date', 'end_date', 'payment_date', 'dcf', 'DF', 'fixed rate', 'PV']
        if (df_input.at[0, 'pay_side_rate'][-1] == '%'):
            self._rate_pay = float(df_input.at[0, 'pay_side_rate'][:-1]) / 100.0
        else:
            self._rate_pay = float(df_input.at[0, 'pay_side_rate'])
        if (df_input.at[0, 'rec_side_rate'][-1] == '%'):
            self._rate_rec = float(df_input.at[0, 'rec_side_rate'][:-1]) / 100.0
        else:
            self._rate_rec = float(df_input.at[0, 'rec_side_rate'])
        self._DF_obj_pay = dc.discount_factor(IR_data_name, self._ccy_our_pay, self._valuation_date)
        self._DF_obj_rec = dc.discount_factor(IR_data_name, self._ccy_our_rec, self._valuation_date)

        
    def _create_df_pay(self):
        index_pay = range(self._num_pay_side+1)
        if (self._fix_float_pay=='FLOAT'):
            df_pay_side = pd.DataFrame(index=index_pay, columns=self._names_float)
        elif(self._fix_float_pay=='FIXED'):
            df_pay_side = pd.DataFrame(index=index_pay, columns=self._names_fix)
        return df_pay_side
    
    def _create_df_rec(self):
        index_rec = range(self._num_rec_side+1)
        if (self._fix_float_rec=='FLOAT'):
            df_rec_side = pd.DataFrame(index=index_rec, columns=self._names_float)
        elif(self._fix_float_rec=='FIXED'):
            df_rec_side = pd.DataFrame(index=index_rec, columns=self._names_fix)
        return df_rec_side        
    
    def add_cash_flow_pay(self):
        lag = 2 #days TODO given input file??
        df_pay_side = self._create_df_pay()
        end_date_list = wd.create_end_date(self._valuation_date, self._roll_pay, 'following', self._num_pay_side, lag)
        start_date_list = wd.create_start_date(self._valuation_date, self._roll_pay, 'following', self._num_pay_side, lag)
        DF_list = self._DF_obj_pay.get_DF_list()
        df_DF = pd.DataFrame(DF_list, columns=['num', 'date', 'DF'])
        df_DF_date_index = df_DF.set_index('date')
        for i in range(self._num_pay_side+1):
            df_pay_side['start_date'][i] = start_date_list[i]
            df_pay_side['end_date'][i] = end_date_list[i]
            df_pay_side['payment_date'][i] = end_date_list[i]
            df_pay_side['dcf'][i] = calc_day_count_fraction(start_date_list[i], end_date_list[i], int(self._dcc_pay[-3:]))
            df_pay_side['DF'][i] = df_DF_date_index.at[end_date_list[i], 'DF']
            df_pay_side['foward rate'][i] = (df_DF_date_index.at[start_date_list[i], 'DF'] / df_DF_date_index.at[end_date_list[i], 'DF'] -1) /  df_pay_side['dcf'][i]
            df_pay_side['PV'][i] =  df_pay_side['dcf'][i] *  df_pay_side['foward rate'][i] * df_pay_side['DF'][i] * self._notional
        return df_pay_side
    
    def add_cash_flow_rec(self):
        lag = 2
        df_rec_side = self._create_df_rec()
        end_date_list = wd.create_end_date(self._valuation_date, self._roll_rec, 'following', self._num_rec_side, lag)
        start_date_list = wd.create_start_date(self._valuation_date, self._roll_rec, 'following', self._num_rec_side, lag)
        DF_list = self._DF_obj_rec.get_DF_list()
        df_DF = pd.DataFrame(DF_list, columns=['num', 'date', 'DF'])
        df_DF_date_index = df_DF.set_index('date')
        for i in range(self._num_rec_side+1):
            df_rec_side['start_date'][i] = start_date_list[i]
            df_rec_side['end_date'][i] = end_date_list[i]
            df_rec_side['payment_date'][i] = end_date_list[i]
            df_rec_side['dcf'][i] = calc_day_count_fraction(start_date_list[i], end_date_list[i], int(self._dcc_rec[-3:]))
            df_rec_side['DF'][i] = df_DF_date_index.at[end_date_list[i], 'DF']
            df_rec_side['fixed rate'][i] = self._rate_rec
            df_rec_side['PV'][i] =  df_rec_side['dcf'][i] *  df_rec_side['fixed rate'][i] * df_rec_side['DF'][i] * self._notional
        return df_rec_side
    
    def calc_PV(self):
        df_pay_side = self.add_cash_flow_pay()
        df_pay_side =  df_pay_side.drop(0)
        df_rec_side = self.add_cash_flow_rec()
        PV_pay = df_pay_side['PV'].sum()
        PV_rec = df_rec_side['PV'].sum()
        PV = PV_pay - PV_rec
        return PV
        
        
    def get_ccy_our_pay(self):
        return self._ccy_our_pay
    
    def get_ccy_our_rec(self):
        return self._ccy_our_rec
    
    def get_fix_float_pay(self):
        return self._fix_float_pay
    
    def get_fix_float_rec(self):
        return self._fix_float_rec
    
    def get_term(self):
        return self._term
    
    def get_dcc_pay(self):
        return self._dcc_pay
    
    def get_dcc_rec(self):
        return self._dcc_rec
    
    def get_num_pay_side(self):
        return self._num_pay_side 
    
    def get_num_rec_side(self):
        return self._num_rec_side 
    
    def get_df_pay_side(self):
        df_pay = self._create_df_pay()
        return df_pay
    
    def get_df_rec_side(self):
        df_rec = self._create_df_rec()
        return df_rec
    
    def get_rate_pay(self):
        return self._rate_pay
    
    def get_rate_rec(self):
        return self._rate_rec

In [2]:
price_obj = swap_pricer('2018/01/18', 'swap_pricing_input.csv', 'convention.csv', 'IR_data.csv')
price_obj.get_num_rec_side()
price_obj.get_df_pay_side()
test_df = price_obj.get_df_rec_side()
price_obj.get_rate_pay()

0.0

In [3]:
price_obj.add_cash_flow_pay()
price_obj.add_cash_flow_rec()
price_obj.calc_PV()

2227917.973901118

In [4]:
if('0'[-1] == '%'):
    print(float('0'[-1]) / 100.0)
else:
    print(float('0'[-1]))

0.0

In [10]:
import pandas as pd

In [5]:
df_convention = pd.read_csv('convention.csv', index_col=0)
df_convention

       FIXED    FLOAT ROLL
CCY
EUR  ACT/365  ACT/360   6M
GBP  ACT/365  ACT/360   6M
JPY  ACT/365  ACT/360   6M
USD  ACT/365  ACT/360   3M

In [6]:
df_convention.at['JPY', 'FLOAT']

'ACT/360'

In [7]:
df_input = pd.read_csv('swap_pricing_input.csv')
df_input.at[0, 'ccy_our_pay']

'JPY'

In [8]:
year_to_month('10Y')

120

In [9]:
names_float = ['start_date', 'end_date', 'dcc', 'payment_date', 'DF', 'foward rate', 'PV']
index_float = range(21)
test_df = pd.DataFrame(index=index_float, columns=names_float)
test_df

   start_date end_date  dcc payment_date   DF foward rate   PV
0         NaN      NaN  NaN          NaN  NaN         NaN  NaN
1         NaN      NaN  NaN          NaN  NaN         NaN  NaN
2         NaN      NaN  NaN          NaN  NaN         NaN  NaN
3         NaN      NaN  NaN          NaN  NaN         NaN  NaN
4         NaN      NaN  NaN          NaN  NaN         NaN  NaN
5         NaN      NaN  NaN          NaN  NaN         NaN  NaN
6         NaN      NaN  NaN          NaN  NaN         NaN  NaN
7         NaN      NaN  NaN          NaN  NaN         NaN  NaN
8         NaN      NaN  NaN          NaN  NaN         NaN  NaN
9         NaN      NaN  NaN          NaN  NaN         NaN  NaN
10        NaN      NaN  NaN          NaN  NaN         NaN  NaN
11        NaN      NaN  NaN          NaN  NaN         NaN  NaN
12        NaN      NaN  NaN          NaN  NaN         NaN  NaN
13        NaN      NaN  NaN          NaN  NaN         NaN  NaN
14        NaN      NaN  NaN          NaN  NaN         NaN  NaN
15        NaN      NaN  NaN          NaN  NaN         NaN  NaN
16        NaN      NaN  NaN          NaN  NaN         NaN  NaN
17        NaN      NaN  NaN          NaN  NaN         NaN  NaN
18        NaN      NaN  NaN          NaN  NaN         NaN  NaN
19        NaN      NaN  NaN          NaN  NaN         NaN  NaN
20        NaN      NaN  NaN          NaN  NaN         NaN  NaN

# backup 2/18

In [54]:
'''    def _input_csv_read(self, input_file_name):
        with open(input_file_name, 'r') as csvfile:
            reader_obj = csv.reader(csvfile)
            input_list = []
            for row in reader_obj:
                input_list.append(row)
        key = input_list[0]
        value = input_list[1]
        input_dict = dict(zip(key, value))
        return input_dict
'''

"    def _input_csv_read(self, input_file_name):\n        with open(input_file_name, 'r') as csvfile:\n            reader_obj = csv.reader(csvfile)\n            input_list = []\n            for row in reader_obj:\n                input_list.append(row)\n        key = input_list[0]\n        value = input_list[1]\n        input_dict = dict(zip(key, value))\n        return input_dict\n"